dbtfiap:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ja80445.sa-east-1.aws

      # User/password auth
      user: LGFERGULHA
      password: Abcd1234

      role: ACCOUNTADMIN
      database: FIAPDB
      warehouse: AIRBYTE_WAREHOUSE
      schema: dev_lucas_lira
      threads: 4
      client_session_keep_alive: False